# CONFIGURATIONS
WINDOW_WIDTH, WINDOW_HEIGHT = 700, 750
FPS = 60

# COLORS
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)

# PADDLE
PADDLE_HEIGHT = 20
PADDLE_WIDTH_LEVEL_1 = 200
PADDLE_WIDTH_LEVEL_2 = 150
PADDLE_WIDTH_LEVEL_3 = 100
PADDLE_WIDTH_LEVEL_4 = 50
PADDLE_SPEED = 10

# BRICKS
BRICK_WIDTH = 48
BRICK_HEIGHT = 16
BRICK_SPACING = 6
BRICK_ROWS = 2
BRICK_COLS = 14

# BALL
BALL_SPEED = 2
MAX_BALL_SPEED_LEVEL_1 = 3
MAX_BALL_SPEED_LEVEL_2 = 4
MAX_BALL_SPEED_LEVEL_3 = 5
MAX_BALL_SPEED_LEVEL_4 = 6

# SOUND EFFECTS
BALL_HIT_WALL = './assets/sfx/ball_hit_wall.wav'
BALL_HIT_PADDLE = './assets/sfx/ball_hit_paddle.wav'
BALL_HIT_BLOCK = './assets/sfx/ball_hit_block.wav'
BALL_HIT_GREEN = './assets/sfx/green_block_hit.mp3'
BALL_HIT_ORANGE = './assets/sfx/orange_block_hit.mp3'
BALL_HIT_RED ='./assets/sfx/red_block_hit.mp3'
